############################### Style ###############################
use_cdn: true
info:
  theme_name: Volantis # This is theme's name.
  theme_version: "4.3.0" # This is theme's version.
  theme_docs: https://volantis.js.org/ # This is theme's URL.
  theme_repo: https://github.com/volantis-x/hexo-theme-volantis
  cdn:
    #js: https://cdn.jsdelivr.net/gh/XiaoMengXinX/blog/js-v4.0.0/app.js # 注意版本!!!
    #css:
    #first: https://cdn.jsdelivr.net/gh/XiaoMengXinX/blog/css-v4.0.0/first.css
    #style: https://cdn.jsdelivr.net/gh/XiaoMengXinX/blog/css-v4.0.0/style.css

custom_css:
  font_smoothing: true
  navbar:
    height: 64px
    effect: [shadow, blur]
  sidebar:
    effect: [shadow, blur] # [shadow, floatable, blur]
  body:
    effect: [shadow, blur] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      copy_btn: true
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
    note: # style for default note: {% note text %}
      icon: '\f054'
      color: ""
  fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: "Varela Round"
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: '"Varela Round", UbuntuMono, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: "Varela Round"
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
      offset: 0.1rem # Correct baseline for zh-CN
    codefont:
      fontfamily: "Monaco, Menlo, UbuntuMono"
      name: "Monaco"
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
      # name: 'Monaco'
      # url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
      # weight: normal
      # style: normal

navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title: XiaoMengXinX's Blog
  menu:
    - name: 主页
      icon: fas fa-home
      url: /
    #- name: 说说
    #  icon: fas fa-comment
    #url: artitalk?blank
    #  url: artitalk/
    - name: 留言板
      icon: fas fa-book
      url: messages/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
    - name: 其他
      icon: fas fa-ellipsis-v
      rows:
        - name: 归档
          icon: fas fa-archive
          img:
          url: archives/
        - name: 分类
          icon: fas fa-folder-open
          img:
          url: categories/
        - name: 标签
          icon: fas fa-tags
          img:
          url: tags
    - name: 暗黑模式
      icon: fas fa-moon # 可自定义
      toggle: darkmode
  search: 搜索 # Search bar placeholder

############################### Layout ###############################
cover:
  height_scheme: half # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: #https://cdn.jsdelivr.net/gh/xbl233/blog/img/bg.jpg
  logo: # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/256/google_logo.png
  title: 小萌新's Blog
  subtitle: "A salt fish."
  search: # search bar placeholder
  features:
    - name: 主页
      icon: fas fa-home
      img:
      url: /
    #- name: 归档
    #  icon: fas fa-archive
    #  img:
    #  url: archives/
    #- name: 分类
    #  icon: fas fa-folder-open
    #  img:
    #  url: categories/
    #- name: 标签
    #  icon: fas fa-tags
    #  img:
    #  url: tags
    #- name: 说说
    #  icon: fas fa-comment
    #url: artitalk?blank
    #  url: artitalk/
    - name: 留言板
      icon: fas fa-book
      url: messages/
    - name: 关于
      icon: fas fa-info-circle
      img:
      url: about/

rightmenu:
  enable: false
  # hr: 分割线, music: 音乐控制器
  layout: [home] #[home, print, hr, music]
  # 可选功能项
  print:
    name: 打印页面
    icon: fa fa-print
    onclick: document.execCommand('print')
  # 自定义菜单的格式如下
  help:
    name: 常见问题
    icon: fa fa-question
    url: https://volantis.js.org/faqs/
  examples:
    name: 示例博客
    icon: fa fa-rss
    url: https://volantis.js.org/examples/
  contributors:
    name: 加入社区
    icon: fa fa-fan fa-spin
    url: https://volantis.js.org/contributors/
  source_docs:
    name: 本站源码
    icon: fa fa-code-branch
    url: https://github.com/volantis-x/volantis-docs/
  source_theme:
    name: 主题源码
    icon: fa fa-code-branch

site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [social, license, analytics, info, copyright]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:xibaole2333@gmail.com
    - icon: fab fa-github
      url: https://github.com/XiaoMengXinX
  #    - icon: fas fa-headphones-alt
  #      url: https://music.163.com/#/user/home?id=63035382
  analytics: >
    <span id="lc-sv">本站总访问量为 <span id='number'><i class="fas fa-circle-notch fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span id="lc-uv">访客数为 <span id='number'><i class="fas fa-circle-notch fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
    <!--- <script type="text/javascript">var aTagArr = [].slice.apply(document.getElementsByTagName("a"));aTagArr.forEach(function (e, i) {e.href.indexOf("artitalk?blank") > -1 ? [artitalk, e.href] = ["/artitalk", "javascript:window.open(artitalk);"] : null;});</script> --->
  copyright: '[Copyright © 2017-2021 XiaoMengXinX](https://blog.onetext.xyz/)<br><a href="https://blog.onetext.xyz/sitemap.xml">网站地图</a>'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: "<br>"

  # 文章布局
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category, date, wordcount, counter]
    # ----------------
    # 文章页脚组件
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fas fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 相关文章，需要安装插件 (for layout: post)
      # npm i hexo-related-popular-posts
      related_posts:
        enable: false
        title: 相关文章
        icon: fas fa-bookmark
        max_count: 5
        # 设为空则不使用文章头图
        placeholder_img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/046.jpg
      # ----------------
      # 版权声明组件 (for layout: post/docs)
      copyright:
        enable: true
        permalink: "本文链接："
        content:
          - "博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议"
          - permalink
      # ----------------
      # 打赏组件 (for layout: post/docs)
      donate:
        enable: false
        images:
          - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
          - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [updated, tags, share]
    # meta library
    meta_library:
      # 默认文章作者（可在 front-matter 中覆盖）
      author:
        avatar: https://cdn.jsdelivr.net/gh/XiaoMengXinX/blog/img/avatar.jpg
        name: lz已经是条咸鱼了
        url: https://github.com/XiaoMengXinX/
      # 文章创建日期
      date:
        icon: fas fa-edit
        title: ""
        format: "YYYY.MM.DD" # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fas fa-edit
        title: "更新于："
        format: "YYYY.MM.DD" # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fas fa-folder-open
      top:
        icon: fas fa-angle-double-up
      # 文章浏览计数
      counter:
        icon: fas fa-eye
        unit: "次浏览"
      # 文章评论数量：只支持 valine
      valinecount:
        icon: fas fa-comment-dots
        desc: "" # 条评论
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fas fa-keyboard
        icon_duration: fas fa-hourglass-half
      # 文章标签
      tags:
        icon: fas fa-hashtag
      # 分享
      share:
        - id: qq
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
        - id: qzone
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
        #- id: weibo
        #img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
        - id: # qrcode # 当id为qrcode时需要安装插件  npm i hexo-helper-qrcode
          img: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/wechat.png
        - id: telegram
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png

sidebar:
  # 主页、分类、归档等独立页面
  for_page: [info, category, tagcloud, webinfo]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
      shape: rectangle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: "#999"
      end_color: "#555"

    # ---------------------------------------
    # qrcode widget
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 64px # Automatic height if not set
      images:
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # ---------------------------------------
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fas fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: "文章数目："
          unit: "篇"
        runtime:
          enable: true
          data: "2020/04/01" # 填写建站日期
          text: "已运行时间："
          unit: "天"
        wordcount:
          enable: true
          text: "本站总字数：" # 需要启用 wordcount
          unit: "字"
        siteuv:
          enable: true
          text: "本站访客数：" # 需要启用 busuanzi
          unit: "人"
        sitepv:
          enable: true
          text: "本站总访问量：" # 需要启用 busuanzi
          unit: "次"
        lastupd:
          enable: true
          friendlyShow: true # 更友好的时间显示
          text: "最后活动时间："
          unit: "日"
    #info:
    #  class: text
    #  display: [desktop] # [desktop, mobile]
    #  pid: homeinfo
    #  header:
    #    icon: fas fa-info-circle
    #    title: 提示
    #  content:
    #    - '本站使用了自定义右键菜单，要调用系统右键菜单请使用 ctrl + 右键 ~'

comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, twikoo, waline, minivaline, disqus, disqusjs, gitalk, vssue, livere, isso, hashover
  valine:
    js: https://cdn.jsdelivr.net/gh/XiaoMengXinX/blog/js-v4.0.0/valine.js
    path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是valine的问题
    placeholder: 快来评论吧~ # 评论占位提示
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder emojiCDN emojiMaps] 选项
    appId: AWnQI2G44xg3M3sckKnrq1of-gzGzoHsz # your appId
    appKey: YqWzSyLNnyCoISL4B5K7FXHQ # your appKey

plugins:
  highlightjs:
    enable: #true # Please set hexo.config.highlight.enable = false !!!
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10/build/highlight.min.js
    css: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10/build/styles/solarized-light.min.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: true
    js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.6/dist/scrollreveal.min.js
    distance: 32px
    duration: 800 # ms
    interval: 20 # ms
    scale: 1 # 0.1~1

  # Codeblock Copy Button
  clipboard:
    enable: true
    js: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  ######## Plugins for SEO:

  # npm i hexo-wordcount
  wordcount:
    enable: true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    enable: true
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # fontawesome animation
  fontawesome_animation:
    enable: #true
    css: https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css

  # Typing Effects
  comment_typing:
    enable: true
    js: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: fixed # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true # shuffle playlist
    duration: 10000 # Duration (ms)
    fade: 1500 # fade duration (ms) (Not more than 1500)
    images: # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/XiaoMengXinX/blog/img/bg3.jpg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: false
    js:
      aplayer: https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      meting: https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease # netease, tencent, kugou, xiami, baidu
    type: playlist # song, playlist, album, search, artist
    id: 2111645608 # song id / playlist id / album id / search keyword
    # Optional
    fixed: false # enable fixed mode
    theme: "#1BCDFC" # main color
    autoplay: false # audio autoplay
    order: random # player play order, values: 'list', 'random'
    loop: all # player loop play, values: 'all', 'one', 'none'
    volume: 0.2 # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 320px # list max height
    list_folded: true

  pjax:
    enable: true
    timeout: 5000 # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false # When set to true, Pjax appends a timestamp  to skip the browser cache.
    animation: false # false, nprogress, circle
    banUrl: # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      - "/artitalk/" # artitalk 不支持 pjax
      # - '/bb/'           # bbtalk 不支持 pjax

  # 从 issues 加载动态数据
  # {% issues sites/timeline/friends | api=xxx | group=key:a,b,c %}
  # 例如：
  # {% issues sites | api=https://api.github.com/repos/volantis-x/examples/issues?sort=updated&state=open&page=1&per_page=100 | group=version:latest,v6,v5,v4,v3,v2,v1,v0 %}

  # 暗黑模式 darkmode
  # 样式：source/css/_plugins/dark.styl
  # 开关按钮：在 navbar.menu 中添加：
  # - name: 暗黑模式 # 可自定义
  #   icon: fas fa-moon # 可自定义
  #   toggle: darkmode
  darkmodejs:
    enable: true

  artitalk:
    # Set `layout: artitalk` to enable in page
    # 配置项按照yml格式继续填写即可
    appId: AWnQI2G44xg3M3sckKnrq1of-gzGzoHsz # your appID
    appKey: YqWzSyLNnyCoISL4B5K7FXHQ # your appKEY
    serverURL: https://avoscloud.com #leancloud绑定的安全域名，使用国际版的话不需要填写
    # lang: # 语言设置，zh为汉语，en为英语，es为西班牙语。默认为汉语
    # pageSize: #每页说说的显示数量
    # shuoPla: #在编辑说说的输入框中的占位符
    # avatarPla: #自定义头像url的输入框的占位符
    # motion: #加载动画的开关，1为开，0为关，默认为开
    # bgImg: #说说输入框背景图片url
    #color1: e91e63 #说说背景颜色1&按钮颜色1
    #color2: e91e63 #说说背景颜色2&按钮颜色2
    # color3: #说说字体颜色
    # cssUrl: #自定义css接口

color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: "#FFC0CB"
    # 链接色
    link: "#2196f3"
    # 按钮色
    button: "#ffcbd3"
    # 鼠标放到交互元素上时的色
    hover: "#ff9fb4"
    # 主题色块内部的文字颜色
    inner: "#fff"
    # 选中区域文字的背景颜色
    selection: "alpha(#2196f3, 0.2)"
  # ------------
  # 亮色主题（默认）
  light:
    # 网站背景色
    site_bg: "#f4f4f4"
    # 网站背景上的文字
    site_inner: "#fff"
    # 网站页脚文字
    site_footer: "#f3f1f4"

    # 卡片背景色
    card: "#fff"
    # 卡片上的普通文字
    text: "#444"

    # 区块和代码块背景色
    block: "#f6f6f6"
    # 代码块高亮时的背景色
    codeblock: "#fff5f6"
    # 行内代码颜色
    inlinecode: "#D56D28"

    # 文章部分
    h1: "#444"
    h2: "#444"
    h3: "#444"
    h4: "#444"
    h5: "#444"
    h6: "#444"
    p: "#444"

    # 列表文字
    list: "#666"
    # 列表 hover 时的文字
    list_hl: "mix($color-theme, #000, 80)"
    # 辅助性文字
    meta: "#888"
  # ------------
  # 暗色主题
  dark:
    # 网站背景色
    site_bg: "#222"
    # 网站背景上的文字
    site_inner: "#eee"
    # 网站页脚文字
    site_footer: "#aaa"
    # 卡片背景色
    card: "#444"
    # 卡片上的普通文字
    text: "#eee"

    # 区块和代码块背景色
    block: "#3a3a3a"
    # 代码块高亮时的背景色
    codeblock: "#343a3c"
    # 行内代码颜色
    inlinecode: "#D56D28"

    # 文章部分
    h1: "#eee"
    h2: "#eee"
    h3: "#ddd"
    h4: "#ddd"
    h5: "#ddd"
    h6: "#ddd"
    p: "#bbb"

    # 列表文字
    list: "#aaa"
    # 列表 hover 时的文字
    list_hl: "mix($color-theme, #fff, 80)"
    # 辅助性文字
    meta: "#888"
    # 夜间图片亮度
    brightness: 70%
